---
# Panel to control alarm system
#
# https://www.home-assistant.io/components/alarm_control_panel.manual/
#
alarm_control_panel:
  # TODO: review settings
  - platform: manual
    code: !secret alarm_code
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
