---
# The Home Assistant Cloud allows you to quickly integrate your local
# Home Assistant with various cloud services like Amazon Alexa and Google Home.
#
# https://www.home-assistant.io/components/cloud/
#
cloud:
  google_actions:
    # entity and domain filter in the Home Assistant UI
    entity_config:
      sensor.temperature_parents:
        name: Température de la chambre des parents
        aliases:
          - Température de la suite parentale
      sensor.temperature_salon:
        name: Température du salon
      sensor.temperature_noah:
        name: Température de la chambre de Noah
      sensor.temperature_soren:
        name: Température de la chambre de Sören
      sensor.temperature_athenais:
        name: Température de la chambre d'Athénaïs
      sensor.temperature_sous_sol:
        name: Température du sous-sol
      sensor.temperature_bureau:
        name: Température du bureau
      switch.prise_tv_switch:
        name: Prise télé
      switch.prise_pc_switch:
        name: Prise PC
      binary_sensor.porte_sous_sol:
        name: Porte du Sous-Sol
        aliases:
          - Porte du garage
      binary_sensor.porte_d_entree:
        name: Porte d'entrée
        aliases:
          - Porte principale
