---
# Configures the official Home Assistant frontend.
#
# https://www.home-assistant.io/components/frontend/
#

# Enable config panel in UI
frontend:
  # We can define additional/custom themes for the frontend here.
  themes: !include_dir_merge_named ../themes
