---
# The recorder component is storing details in a database which
# then are handled by the history component.
#
# https://www.home-assistant.io/components/recorder/
#
recorder:
  # Use a MariaDB on my NAS
  db_url: !secret db_url

  # The number of days of history to keep in the recorder database
  purge_keep_days: 3

  # How often (in days) the purge task runs
  purge_interval: 1

  # select entites to be included
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - alarm_control_panel
      - sun
      - vacuum
      - device_tracker
      - input_select
      - input_boolean
      - script
      - automation
      - person
      - variable
