---
# E: This handles the loading of my scripts (YAML and UI)
# F: Permet de charger mes scripts (YAML et dans UI)
#
# https://www.home-assistant.io/integrations/script
# https://www.home-assistant.io/docs/configuration/splitting_configuration/#example-combine-include_dir_merge_list-with-automationsyaml
#
script ui: !include ../scripts.yaml
script manual: !include_dir_named ../scripts
