---
# Activates the Z-Wave component. I have several Z-Wave based devices in my
# Home Assistant system. I use a Aeotec Z-Stick (gen 5) as my controller device.
#
# https://www.home-assistant.io/docs/z-wave/installation
#
zwave:
  # The USB port where the Aeotech Z-Stick is connected to.
  usb_path: /dev/ttyACM0

  device_config: !include ../zwave_device_config.yaml
