homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret altitude_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:
logger:
#  default: info

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sensor
      - switch
      - media_player

recorder:
  include:
    domains:
      - sensor
      - switch
      - media_player

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: rfxtrx
    devices:
      0a520100f30100624e0389:
        name: ext√©rieur
        data_type:
         - Humidity
         - Temperature
    automatic_add: True

# Text to speech
tts:
  - platform: google
    language: 'fr'

# Cloud
cloud:

#Xiaopi Gateway
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret gateway_xiaomi

#Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids: !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

#RFXCOM
rfxtrx:
  device: /dev/ttyUSB0

#ZWAVE
zwave:
  usb_path: /dev/ttyACM0

#MQTT
mqtt:
  broker: 192.168.1.28
  username: !secret mqtt_username
  password: !secret mqtt_password

timer:
  redemande_leve_du_soleil:
    duration: '00:15:00'

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include scripts.yaml
