homeassistant:
  name: Maison

  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret altitude_home

  unit_system: metric
  time_zone: Europe/Paris

  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction:
logger:
#  default: info

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor


recorder:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
#weather:

# Sensors
sensor:
  - platform: yr
  - platform: rfxtrx
    devices:
      0a520100f30100624e0389:
        name: extérieur
        data_type:
         - Humidity
         - Temperature
    automatic_add: True
  - platform: template
    sensors:
      presence_couloir_temperature:
        friendly_name: 'Temperature couloir'
        value_template: '{{states.sensor.presence_motion_couloir.attributes.temperature}}'
        unit_of_measurement: °C

      presence_couloir_light_level:
        friendly_name: 'Luminosité couloir'
        value_template: '{{states.sensor.presence_motion_couloir.attributes.lux}}'
        unit_of_measurement: lux
  - platform: mqtt
    state_topic: "home/piscine/temperature"
    name: "Température piscine"
    unit_of_measurement: "°C"

  - platform: darksky
    api_key: !secret darksky
    update_interval: 00:05
    monitored_conditions:
      - summary
      # - nearest_storm_distance
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - temperature
      # - apparent_temperature
      # - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      # - pressure
      - visibility
      # - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max
      - uv_index

# Text to speech
tts:
  - platform: google
    language: 'fr'

# Cloud
cloud:

#Xiaopi Gateway
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret gateway_xiaomi

#Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids: !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

#RFXCOM
rfxtrx:
  device: /dev/ttyUSB0

#ZWAVE
zwave:
  usb_path: /dev/ttyACM0

#MQTT
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password

timer:
  redemande_leve_du_soleil:
    duration: '00:15:00'

input_select:
  house_mode:
    name: House mode
    options:
      - Présence
      - Nuit
      - Innocupé
      - Sécurisé

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include scripts.yaml
