---
# Launch my Xiaomi Vacuum in the living room avoiding potential obstacles
#
# https://www.home-assistant.io/components/vacuum/
# https://www.home-assistant.io/components/vacuum.xiaomi_miio/
#
alias: Lance Rocky dans le salon en Ã©vitant les obstacles
sequence:
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.rocky
      fan_speed: balanced
  - service: xiaomi_miio.vacuum_clean_zone
    data_template:
      entity_id: vacuum.rocky
      repeats: "{{ repetition | default(1) }}"
      zone:
        # Avoid zone with lot of stuff, curtains, chairs and small carpets
        - [25600, 25600, 30000, 29300]
        - [25500, 29300, 27800, 32600]
  - service: logbook.log
    data_template:
      name: Rocky
      message: starts cleaning the living room (safe mode)
      entity_id: vacuum.rocky
      domain: vacuum

  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacuum_need_to_be_emptied
