wiki:
  primary-color: "#000000"
  accent-color: "#66e62bdb"
  dark-primary-color: "#6c7168"
  light-primary-color: "#808080"
  primary-text-color: "#ffffff"
  text-primary-color: "var(--primary-text-color)"
  cch-all-tabs-color: "#c1c1c1"
  secondary-text-color: "#181917"
  disabled-text-color: "#696d68"
  label-badge-border-color: "green"
  primary-background-color: "#a6a9a3"
  secondary-background-color: "#383C45"
  divider-color: "rgba(166, 169, 163, 0.35)"
  table-row-background-color: "#80808094"
  table-row-alternative-background-color: "#b7b9b3ad"
  sidebar-icon-color: "rgba(255, 255, 255, 0.41)"
  sidebar-background-color: "#a6a9a3"
  paper-listbox-color: "var(--primary-color)"
  paper-listbox-background-color: "#b7b9b3"
  paper-grey-50: "var(--primary-text-color)"
  paper-grey-200: "#3e4248"
  paper-card-header-color: "var(--accent-color)"
  paper-card-background-color: "#71756e"
  paper-dialog-background-color: "#1f1f1f"
  paper-item-icon-color: "var(--primary-text-color)"
  paper-item-icon-active-color: "#ffbc00f2"
  paper-item-icon_-_color: "green"
  paper-item-selected_-_background-color: "#434954"
  paper-tabs-selection-bar-color: "green"
  label-badge-red: "var(--accent-color)"
  label-badge-text-color: "var(--primary-text-color)"
  label-badge-background-color: "#2E333A"
  paper-toggle-button-checked-button-color: "var(--accent-color)"
  paper-toggle-button-checked-bar-color: "var(--accent-color)"
  paper-toggle-button-checked-ink-color: "var(--accent-color)"
  paper-toggle-button-unchecked-button-color: "var(--disabled-text-color)"
  paper-toggle-button-unchecked-bar-color: "var(--disabled-text-color)"
  paper-toggle-button-unchecked-ink-color: "var(--disabled-text-color)"
  paper-slider-knob-color: "var(--accent-color)"
  paper-slider-knob-start-color: "var(--accent-color)"
  paper-slider-pin-color: "var(--accent-color)"
  paper-slider-active-color: "var(--accent-color)"
  paper-slider-container-color: "linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat"
  paper-slider-secondary-color: "var(--secondary-background-color)"
  paper-slider-disabled-active-color: "var(--disabled-text-color)"
  paper-slider-disabled-secondary-color: "var(--disabled-text-color)"
  google-red-500: "#E45E65"
  google-green-500: "#39E949"

  off-color: "#3c331d"