---
# Zone for work
#
# https://www.home-assistant.io/components/zone/
#
- name: Travail Benoit
  latitude: !secret latitude_work_B
  longitude: !secret longitude_work_B
  radius: 250
  passive: false
  icon: mdi:airplane-takeoff
  
- name: Travail Alex
  latitude: !secret latitude_work_A
  longitude: !secret longitude_work_A
  radius: 250
  passive: false
  icon: mdi:owl