---
# Pool Water temperature
#
# To be used with custom component ha-pool_pump
#
# https://github.com/oncleben31/ha-pool_pump
#
pool_temperature:
  name: Température Piscine
  icon: mdi:coolant-temperature
  mode: slider
  min: 0
  max: 30
  unit_of_measurement: °C