---
# Welcome to my Home Assistant configuration!
#
# Don't be scared by the size of my configuration file...
# I'm inspired by the strucutre propsed by Franck Nijhof.
#
# This system is very modular and very differently structured
# compared to other configurations you'll find online.
#
# Basically, each file in the repository does 1 (one, uno, eins)
# thing only! Click through it, you'll get it pretty fast.
#
# The configuration.yaml is only used to bootstrap the system
# and contains some minimal, but vital, settings.
#
# https://github.com/frenck/home-assistant-config
# https://www.youtube.com/watch?v=lndeybw21PY
#
homeassistant:
  # Name of this Home Assistant instance... Some French touch ;)
  name: Maison

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret altitude_home

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

  # Load packages
  packages: !include_dir_named integrations

# This integration doesn't work in split configuration see #48
hacs:
  token: !secret my_github_access_token
