button_card_templates:
  vacuum_zone:
    aspect_ratio: 1/1
    color_type: card
resources:
  - type: js
    url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
  - type: js
    url: /local/linky-card.js?v=4
  - type: js
    url: /community_plugin/lovelace-card-tools/card-tools.js
  - type: js
    url: /community_plugin/lovelace-auto-entities/auto-entities.js
  - type: js
    url: /customcards/weasley-card.js
  - type: js
    url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
  - type: js
    url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/canvas-gauge-card/canvas-gauge-card.js
  - type: js
    url: /community_plugin/lovelace-card-modder/card-modder.js
title: Maison
views:
  - badges:
      - sun.sun
      - sensor.aurade_next_rain
      - sensor.aurade_weather_alert
    cards:
      - entity: weather.dark_sky
        name: Météo DarkSky
        type: weather-forecast
      - entities:
          - entity: sensor.exterieur_temperature
          - entity: sensor.exterieur_humidity
          - entity: sensor.temperature_piscine
        title: Extérieur
        type: glance
      - entity: weather.aurade
        type: weather-forecast
      - entities:
          - entity: sensor.temperature_salon
          - entity: sensor.temperature_parents
          - entity: sensor.temperature_noah
          - entity: sensor.temperature_athenais
          - entity: sensor.temperature_soren
          - entity: sensor.temperature_cave
        show_header_toggle: false
        title: Températures
        type: entities
    icon: 'mdi:home'
    path: default_view
    title: Maison
  - badges: []
    cards:
      - cards:
          - cards:
              - color_type: card
                entity: script.vacuum_workday_sequence
                size: 30%
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.stop_vacuum_workday_sequence
                icon: 'mdi:robot-vacuum'
                label_template: >
                  return (states['sensor.vacuum_cleaner_status_sensor'].state)
                  +' (' + (states['sensor.vacuum_battery'].state) + ' %)'
                name: Lancer la routine de Rocky
                show_label: true
                state:
                  - spin: true
                    value: 'on'
                tap_action:
                  action: toggle
                type: 'custom:button-card'
            type: horizontal-stack
          - cards:
              - entity: input_boolean.vacuum_can_clean_the_kitchen
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_kitchen
                icon: 'mdi:silverware-fork-knife'
                name: Cuisine
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_the_living_room_safe
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_livingroom_safe
                icon: 'mdi:sofa'
                name: "Salon \U0001F6E1"
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_the_living_room
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_livingroom
                icon: 'mdi:sofa'
                name: Salon
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_the_carpet
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_on_the_carpet
                icon: 'mdi:camera-metering-matrix'
                name: Tapis
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
            type: horizontal-stack
          - cards:
              - entity: input_boolean.vacuum_can_clean_the_entrance
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.vacuum_can_clean_the_entrance
                icon: 'mdi:door'
                name: Entrée
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_the_coridor
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_the_coridor
                icon: 'mdi:treasure-chest'
                name: Couloir
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_the_office
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_office
                icon: 'mdi:laptop'
                name: Bureau
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_kids_bathroom
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_kids_bathroom
                icon: 'mdi:shower'
                name: SdB Enfants
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
            type: horizontal-stack
          - cards:
              - entity: input_boolean.vacuum_can_clean_athenais_bedroom
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_athenais_bedroom
                icon: 'mdi:hotel'
                name: Athénaïs
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_noah_bedroom
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_noah_bedroom
                icon: 'mdi:hotel'
                name: Noah
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_soren_bedroom
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_soren_bedroom
                icon: 'mdi:hotel'
                name: Sören
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
              - entity: input_boolean.vacuum_can_clean_parental_suite
                hold_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.launch_vacuum_in_parental_suite
                icon: 'mdi:human-male-female'
                name: Parents
                tap_action:
                  action: toggle
                template: vacuum_zone
                type: 'custom:button-card'
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: script.vacuum_map_construct
        show_header_toggle: false
        title: Scripts de la routine
        type: entities
      - entities:
          - entity: input_boolean.vacuum_need_to_be_emptied
        type: entities
    icon: 'mdi:robot-vacuum'
    title: Rocky
  - badges: []
    cards:
      - entities:
          - entity: sensor.exterieur_temperature
          - entity: sensor.temperature_piscine
        type: entities
      - entities:
          - entity: binary_sensor.protection_window
          - entity: sensor.aurade_uv
        type: entities
      - card:
          elements:
            - entity: sensor.dark_sky_uv_index
              gauge:
                animationDuration: 1500
                animationRule: linear
                borders: 'no'
                colorValueBoxRect: '#222'
                colorValueBoxRectEnd: '#333'
                height: 200
                highlights:
                  - color: 'rgba(247, 228, 1, .75)'
                    from: 2.5
                    to: 5.5
                  - color: 'rgba(40, 149, 0, .75)'
                    from: 0
                    to: 2.5
                  - color: 'rgba(248, 123, 1, .75)'
                    from: 5.5
                    to: 7.5
                  - color: 'rgba(216, 23, 0, .75)'
                    from: 7.5
                    to: 10.5
                  - color: 'rgba(75, 46, 154, .75)'
                    from: 10.5
                    to: 13
                majorTicks:
                  - '0'
                  - '1'
                  - '2'
                  - '3'
                  - '4'
                  - '5'
                  - '6'
                  - '7'
                  - '8'
                  - '9'
                  - '10'
                  - '11'
                  - '12'
                  - '13'
                maxValue: 13
                minValue: 0
                minorTicks: 5
                needleCircleInner: false
                needleCircleOuter: true
                needleCircleSize: 7
                needleType: arrow
                needleWidth: 4
                startAngle: 40
                strokeTicks: true
                ticksAngle: 280
                title: UV Index
                type: radial-gauge
                valueBox: true
                valueBoxBorderRadius: 10
                valueDec: 2
                valueInt: 2
                width: 200
              style:
                left: 50%
                top: 50%
              type: 'custom:canvas-gauge-card'
          image: /local/UV_indice_background.png
          type: picture-elements
        style:
          border-radius: 25px
        type: 'custom:card-modder'
      - entities:
          - entity: sensor.wifi_signal_sensor
          - entity: input_boolean.stop_deep_sleep
          - entity: binary_sensor.capteur_piscine
        type: entities
    icon: 'mdi:pool'
    title: Piscine
  - badges: []
    cards:
      - entity: alarm_control_panel.ha_alarm
        name: Alarme
        states:
          - arm_home
          - arm_away
        type: alarm-panel
      - entities:
          - entity: input_select.house_mode
        type: glance
      - entities:
          - entity: binary_sensor.main_door
          - entity: binary_sensor.garage_door
        type: glance
      - entities:
          - entity: binary_sensor.water_leak_sensor_buanderie
        show_header_toggle: false
        title: Détection fuite d'eau
        type: entities
      - entities:
          - entity: binary_sensor.motion_house_meta
          - entity: variable.last_motion
          - entity: binary_sensor.motion_sensor_livingroom
        show_header_toggle: false
        title: Détecteurs de mouvement
        type: entities
    icon: 'mdi:shield-home'
    panel: false
    title: Sécurité
  - badges: []
    cards:
      - entities:
          - entity: switch.prise_pc_switch
          - entity: switch.prise_tv_switch
        show_state: false
        title: Prises commandées
        type: glance
      - entity: sensor.prise_pc_power
        max: 300
        min: 0
        name: Conso PC
        severity:
          green: 0
          red: 200
          yellow: 7
        theme: default
        type: gauge
      - entity: sensor.prise_tv_power
        max: 150
        min: 0
        name: Conso TV
        severity:
          green: 0
          red: 100
          yellow: 25
        theme: default
        type: gauge
      - entity: sensor.linky
        type: 'custom:linky-card'
    icon: 'mdi:power-plug'
    title: Énerige
  - badges:
      - binary_sensor.temp_falling
      - binary_sensor.temp_rising
    cards:
      - card:
          title: Lights on
          type: glance
        filter:
          exclude:
            - entity_id: light.home_hassistant
          include:
            - domain: light
              options:
                tap_action:
                  action: toggle
              state: 'on'
        show_empty: true
        type: 'custom:auto-entities'
      - entities:
          - entity: sensor.trajet_maison_travail_benoit
          - entity: sensor.trajet_maison_travail_alex
        title: Trajets
        type: glance
      - entities:
          - card:
              head:
                label: Désactivées
                type: section
              type: 'custom:fold-entity-row'
            filter:
              include:
                - domain: automation
                  state: 'off'
            show_empty: false
            type: 'custom:auto-entities'
          - card:
              head:
                label: Activées
                type: section
              type: 'custom:fold-entity-row'
            filter:
              include:
                - domain: automation
                  state: 'on'
            show_empty: false
            type: 'custom:auto-entities'
        title: Automatismes
        type: entities
      - entities:
          - head: group.all_scripts
            type: 'custom:fold-entity-row'
        show_header_toggle: false
        title: Scripts
        type: entities
      - card:
          title: Tracker Home
          type: glance
        filter:
          include:
            - domain: device_tracker
              state: home
        show_empty: true
        type: 'custom:auto-entities'
      - entities:
          - entity: sensor.illumination_158d0001e575b0
          - entity: sensor.humidity_cave
        type: entities
    icon: 'mdi:robot'
    title: Automatismes
  - badges:
      - sensor.plex
    cards:
      - entity: media_player.tele
        type: media-control
      - entity: media_player.google_home
        type: media-control
      - entity: media_player.samsung_led48_ue48h6200
        type: media-control
    icon: 'mdi:theater'
    title: Média
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.xiaomi_gateway
          - entity: binary_sensor.rocky
          - entity: binary_sensor.hue_gateway
          - entity: binary_sensor.nas
          - entity: binary_sensor.google_home
        title: Systèmes
        type: glance
      - entities:
          - entity: binary_sensor.blizzard
          - entity: sensor.speedtest_ping
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
        title: Internet
        type: glance
      - card:
          show_header_toggle: false
          title: Batteries faibles
          type: entities
        filter:
          exclude:
            - domain: vacuum
            - entity_id: '*pressure*'
            - entity_id: '*humidity*'
            - entity_id: sensor.presence_couloir_temperature
            - entity_id: sensor.presence_couloir_light_level
          include:
            - attributes:
                battery_level: <= 30
              options:
                secondary_info: 'Battery_level: [[ {entity}.attributes.battery_level ]]'
                type: 'custom:secondaryinfo-entity-row'
        show_empty: true
        type: 'custom:auto-entities'
      - entities:
          - entity: sensor.hacs
        title: Mise à jour
        type: entities
      - entities:
          - entity: sensor.processor_use
          - entity: sensor.disk_use_percent
          - entity: sensor.memory_use_percent
          - entity: sensor.cpu_temperature
          - entity: sensor.last_boot
        show_header_toggle: false
        title: Raspberry
        type: entities
      - entities:
          - zwave.aeotec_zw090_zstick_gen5_eu
          - zwave.detecteur_de_fumee
          - zwave.prise_tv
          - zwave.prise_pc
        title: Z-Wave
        type: entities
      - card:
          show_header_toggle: false
          title: Entites indisponibles
          type: entities
        filter:
          exclude:
            - domain: vacuum
            - entity_id: '*pressure*'
            - entity_id: '*humidity*'
            - entity_id: sensor.presence_couloir_temperature
            - entity_id: sensor.presence_couloir_light_level
            - entity_id: group.all_vacuum_cleaners
          include:
            - state: unknown
        show_empty: true
        type: 'custom:auto-entities'
      - entities:
          - entity: vacuum.rocky
          - entity: sensor.vacuum_cleaner_error_sensor
        show_header_toggle: false
        title: Rocky
        type: entities
    icon: 'mdi:lan'
    title: Réseau
  - badges: []
    cards:
      - fontname: itcblkad_font
        locations:
          - Maison
          - Travail
          - Collège
          - École
        lost: Perdu
        travelling: En voyage
        type: 'custom:weasley-card'
        wizards:
          - entity: person.benoit
            name: Benoit
          - entity: device_tracker.hermiones_phone
            name: Alex
          - entity: calendar.ron
            name: Noah
          - entity: calendat.noah
            name: Athénaïs
          - entity: calendar.ginny
            name: Sören
      - aspect_ratio: '16:9'
        entities:
          - entity: zone.home
          - entity: zone.travail_alex
          - entity: zone.travail_benoit
          - entity: zone.college
          - entity: zone.ecole
        type: map
    icon: 'mdi:map-marker'
    panel: false
    title: Map
