---
# This binary sensor, track the plugged state of the ZoÃ©
#
# https://github.com/epenet/hassRenaultZE
# https://www.home-assistant.io/components/binary_sensor.template/
#
platform: template
sensors:
  zoe_plugged:
    friendly_name: "BranchÃ©e"
    device_class: plug
    value_template: >-
      {%- if is_state_attr('sensor.zoe', 'plugged', true) 
      -%}
      true
      {%- else -%}
      false
      {%- endif %}