---
# Check if lights are still on when sun up
#
# If yes send a notification on telegram asking what to do: nothing, switch
# off or check again in 15 minutes
#
# https://www.home-assistant.io/components/sun/
#

# Main automation checking the state of the light
- alias: Eteindre éclairage au levé du soleil
  initial_state: true
  trigger:
    - event: sunrise
      offset: "0:15:00"
      platform: sun
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.redemande_leve_du_soleil
  action:
    - data:
        data:
          inline_keyboard:
            - Oui:/eteintLumiere, Non:/do_nothing, Redemande:/redemande
        message:
          Le soleil est levé et il reste des lumières allumées dans le salon.
          Voulez vous les éteindre ?
      service: notify.telegram
  condition:
    - condition: state
      entity_id: light.salon
      state: "on"

# Command received by Telegram to ask again in 15 minutes
- alias: Redemande dans 15 minutes
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /redemande
  action:
    - service: timer.start
      entity_id: timer.redemande_leve_du_soleil
    - service: telegram_bot.edit_message
      data:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.user_id }}"
        message: "OK je te redemande dans 15 minutes"

# Command received by telegram to not switch off the lights
- alias: Ne pas éteindre les lumières
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /do_nothing
  action:
    - service: telegram_bot.answer_callback_query
      data:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: Tu as dis non!
    - service: telegram_bot.edit_message
      data:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.user_id }}"
        message: "OK je laisse les lumières allumées"

# Command received by Telegram to switch off the lights
- alias: Éteindre les lumières
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: /eteintLumiere
  action:
    - service: telegram_bot.answer_callback_query
      data:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: J'éteins les lumières
    - service: light.turn_off
      entity_id: light.salon
    - service: telegram_bot.edit_message
      data:
        message_id: "{{ trigger.event.data.message.message_id }}"
        chat_id: "{{ trigger.event.data.user_id }}"
        message: "Les lumières du salon sont éteintes"
