---
# External Temperature and Humidity coming from Oregon external probe
#
# If need to change batteries, reset the sensor, click Mem and Chanel button
# on base and update the ID of the sensor.
#
# https://www.home-assistant.io/components/sensor.rfxtrx/
#
platform: rfxtrx
devices:
  0a520101100100e52f0189:
    name: ext√©rieur
    data_type:
      - Humidity
      - Temperature
automatic_add: True
