---
# F: Script pour piloter l'aspirateur et reconstruir la carte
# E: Script to pilot the Xioami Vacuum when the map is reseted.
#
# F: Ce script va diriger le robot à plusieurs endroits de la maison
#    pour recontruire la carte.
#
# E: This script will make the robot go in all house to reconstruct
#    the map.
#
# https://www.home-assistant.io/components/vacuum/
# https://www.home-assistant.io/components/vacuum.xiaomi_miio/
# https://www.home-assistant.io//getting-started/scripts/
#
alias: "Constuire la map de Rocky"
description: "Pilote Rocky pour reconstruire la carte de la maison"
mode: single
sequence:
  # first put the fan_speed at minimum to avoid noise
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.rocky
      fan_speed: quiet

  # launch a standard clean during 10 secondes to create the first part of the map
  - service: vacuum.start
    data:
      entity_id: vacuum.rocky
  - delay:
      seconds: 20
  - service: vacuum.stop
    data:
      entity_id: vacuum.rocky
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"
  #
  # send goto_target commands to pilot the robot thru the house
  #
  # Kitchen
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [27500, 25500]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [25500, 22300]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [21600, 21600]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [21600, 24000]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"

  # Living room
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [26000, 31500]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"

  # Office
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [25500, 34100]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [24700, 37100]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"

  # Coridor
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [25500, 37000]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"

  # Kid bathroom
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [20500, 34000]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"

  # Athénaïs' bedroom
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [18000, 35000]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"

  # Noah's bedroom
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [17000, 41000]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"

  # Soren's bedroom
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [20000, 41000]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"

  # Parental suite
  - service: vacuum.send_command
    data:
      entity_id: vacuum.rocky
      command: app_goto_target
      params: [24000, 40000]
  - wait_for_trigger:
      - platform: state
        entity_id: vacuum.rocky
        to: "idle"
